### ISSUE TITLE
Key-pair auth

### ISSUE THREAD

**Issue by GClunies** [TylerHillery/harlequin-adbc#5]
First, thanks for developing this adapter and making Snowflake in Harlequin possible!

Wondering if you know how to configure a connection using [key-pair](https://docs.snowflake.com/en/user-guide/key-pair-auth) authorization? I have tried a connection string in my `harlequin.toml` like
```toml
default_profile = 'mp_profile'

[profiles.mp_profile]
limit = 500
adapter = "adbc"
conn_str = "my_user@my_account&auth_type=auth_jwt&jwt_private_key=/home/my_user/.keys/snowflake/my_rsa_key.p8&jwt_private_key_pkcs8_password=my-passworf"
driver_type = "snowflake"
```

But I get the error
```bash
❯ harlequin
╭─ Harlequin could not connect to your database. ─╮
│ INVALID_ARGUMENT: 260002: password is empty     │
╰─────────────────────────────────────────────────╯

NOTE: 1 of 2 errors shown. Run with textual run --dev to see all errors.
```

I shouldn't need my password if using key pair auth?

Normally I would just create a a password and be done with this, but my employer prefers key-pair.
